
jump-location:
  world: world
  x: -219.56
  y: 20.0
  z: 102.5
  yaw: 230
  pitch: 0

spawn-location:
  world: world
  x: -264.44
  y: 19.0
  z: 108.41
  yaw: 0
  pitch: 0

roles:
  Radahn: false
  Melina: false
  Sans-Ã©clat: true
  Ranni: false
  Godrick: false
  Morgott: true
  Margit: false
  D: false
  Maliketh : false
  Mask d'or : false

pvp-timer: 1
border-size: 400
role-announcement-delay: 15
